version: '3.6'

services:
  nginx:
    build:
      context: .
      dockerfile: ./Docker/nginx/Dockerfile
      cache_from:
        - nginx:latest
    hostname: citrus-nginx
    container_name: citrus-nginx
    restart: unless-stopped
    environment:
      - HTTP_PORT=80
      - APP_NAME=citrus-app
    volumes:
      - .:/app:ro
    ports:
      - "8888:80"
    depends_on:
      - app
  app:
    build:
      context: .
      dockerfile: ./Docker/app/Dockerfile
      cache_from:
        - php:8.1-fpm
    hostname: citrus-app
    container_name: citrus-app
    restart: unless-stopped
    volumes:
      - .:/app
      - app_cache:/var/cache/app
      - app_log:/var/log/app
    environment:
      PHP_IDE_CONFIG: serverName=default
    depends_on:
      - mysql
  mysql:
    build:
      context: .
      dockerfile: ./Docker/mysql/Dockerfile
      cache_from:
        - mysql:latest
    hostname: citrus-mysql
    container_name: citrus-mysql
    restart: unless-stopped
    volumes:
      - citrus-mysql-data:/var/lib/mysql
    ports:
      - "127.0.0.1:3306:3306"

volumes:
  app_cache:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  app_log:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
  citrus-mysql-data:
  public-data: